name: Run tests only

on:
  push:
    branches:
    - "main"
  pull_request:
    branches:
      -"main"

jobs:
  
  Tests:
    runs-on: 'ubuntu-latest'
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v2
    - name: Install Dependencies
      run: npm ci
    - name: Run Tests
      run: exit 1
    - name: Create Issue on Failed workflow
      if: ${{ failure() }}
      uses: dacbd/create-issue-action@main
      with:
        token: ${{ github.token }}
        title: Job failed:${{ github.repository }} - ${{ github.workflow }}
        body: |
          ### Context
          [Failed Run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
          [Codebase](https://github.com/${{ github.repository }}/tree/${{ github.sha }})
          Workflow name - `${{ github.workflow }}`
          Job -           `${{ github.job }}`
          status -        `${{ job.status }}`
        
