name: Run tests only

on:
  push:
    branches:
    - "main"
  pull_request:
    branches:
      -"main"

jobs:
  
  Tests:
    runs-on: 'ubuntu-latest'
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v2
    - name: Install Dependencies
      run: npm ci
    - name: Run Tests
      run: npm test
    - name: Create issue on failure
      if: ${{ job.status != 'success' }}
      uses: actions/create-issue@v1
      with:
        title: Job failed:${{ github.repository }} - ${{ github.workflow }}
        body: |
          The job failed in the ${{ github.workflow }} workflow.

          Job log:

          ```
          ${{ github.event.workflow_run.logs_url }}
          ```
